Preserve interop functions
The interop functions get overwritten by the quill-interop functions when the editor is used. This modification will preserve the intial interop functions.

To test, login, open the editor, then logout and an exception is thrown:
Error: Could not find 'getElementByName' in 'window.interop'.